services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: jobportal-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: jobportal
      RABBITMQ_DEFAULT_PASS: jobportal123