spring.thymeleaf.cache=false
spring.sql.init.mode=never

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

server.port=${PORT:8080}

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# GOOGLE OAUTH
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# BREVO
spring.mail.username=${MAIL_USERNAME}
brevo.api.key=${BREVO_API_KEY}


# AWS
aws.region=ap-south-1
aws.bucket-name=jobportal-resumes-kp

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# RABBITMQ

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=2s
spring.rabbitmq.template.retry.max-attempts=3

spring.rabbitmq.listener.simple.default-requeue-rejected=false
